name:                deep-sessions
version:             0.1.0
github:              dcastrop/deep-sessions
license:             BSD3
author:              David Castro-Perez
maintainer:          david.castro.dcp@gmail.com
copyright:           2017 David Castro-Perez

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Deep embedding of a multiparty session-type language.
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dcastrop/deep-sessions#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- prettyprinter >= 1.6 && < 1.7
- mtl >= 2.2 && < 2.3
- cubicspline >= 0.1 && < 0.2
- extra >= 1.6 && < 1.7

library:
  source-dirs:
  - src
  - examples
  - benchmarks
  ghc-options:
  - -Wall

executables:
  seq-costs:
    main:                Seq.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
